version: '3.8'

services:
  nas-web-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/user/nas-files:/nas-files
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  nas-files:
